# image: atlassian/default-image:2

pipelines:
  default:
    - parallel:
      - step:
          name: 'Build and Test'
          deployment: dev
          script:
            # build the image
            - echo "Your build and test goes here..."
            # - docker build -t my-docker-image .
            - docker compose up --build

            # use the pipe to push the image to AWS ECR
            - pipe: atlassian/aws-ecr-push-image:1.4.1
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                IMAGE_NAME: my-docker-image
